import {Group} from '../shared/shared.model';

export class People extends Group{
  surname: string;
  forename: string;
  gender: string;
  ukCity: string;
  salary: string;
  department: string;
}

// Randomly generated using top 200 lists for surname, male name, female name and uk city
export const people: People[] = [
  {surname: 'Campbell', forename: 'Helen', gender: 'Female', ukCity: 'Burnley', salary: '£10 to £20k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Butler', forename: 'Cynthia', gender: 'Female', ukCity: 'Burnley', salary: '£90 and over', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simpson', forename: 'Janice', gender: 'Female', ukCity: 'Burnley', salary: '£70 to £80k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Elliott', forename: 'Lucille', gender: 'Female', ukCity: 'Burnley', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Walker', forename: 'Shirley', gender: 'Female', ukCity: 'Oxford', salary: '£80 to £90k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Nguyen', forename: 'Marie', gender: 'Female', ukCity: 'Lisburn', salary: '£80 to £90k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Bailey', forename: 'Kenneth', gender: 'Male', ukCity: 'Mansfield', salary: '£80 to £90k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Mitchell', forename: 'David', gender: 'Male', ukCity: 'Exeter', salary: '£10 to £20k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Bryant', forename: 'Connie', gender: 'Female', ukCity: 'Reading', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gomez', forename: 'Ida', gender: 'Female', ukCity: 'Plymouth', salary: '£20 to £30k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Peters', forename: 'Richard', gender: 'Male', ukCity: 'StHelen’s', salary: '£70 to £80k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Howard', forename: 'Amanda', gender: 'Female', ukCity: 'Gosport', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Tran', forename: 'Joshua', gender: 'Male', ukCity: 'Colchester', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Nichols', forename: 'Annie', gender: 'Female', ukCity: 'Gateshead', salary: '£90 and over', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Russell', forename: 'James', gender: 'Male', ukCity: 'Dunfermline', salary: '£10 to £20k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ward', forename: 'Antonio', gender: 'Male', ukCity: 'Ipswich', salary: '£90 and over', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Marshall', forename: 'David', gender: 'Male', ukCity: 'Halifax', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Howard', forename: 'Ronnie', gender: 'Male', ukCity: 'Oxford', salary: '£40 to £50k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'James', forename: 'Pamela', gender: 'Female', ukCity: 'Wallasey', salary: '£60 to £70k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Long', forename: 'Jerry', gender: 'Male', ukCity: 'Coventry', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Kelley', forename: 'Mildred', gender: 'Female', ukCity: 'Dewsbury', salary: '£80 to £90k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Jenkins', forename: 'Karen', gender: 'Female', ukCity: 'Maidenhead', salary: '£80 to £90k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thomas', forename: 'Sue', gender: 'Female', ukCity: 'Gosport', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hughes', forename: 'Stephanie', gender: 'Female', ukCity: 'Keighley', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'King', forename: 'Rachel', gender: 'Female', ukCity: 'Dunfermline', salary: '£10 to £20k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Mendoza', forename: 'Joshua', gender: 'Male', ukCity: 'Wigan', salary: 'Upto £10k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Cruz', forename: 'Patrick', gender: 'Male', ukCity: 'Sheffield', salary: 'Upto £10k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Peters', forename: 'Dorothy', gender: 'Female', ukCity: 'Aylesbury', salary: '£20 to £30k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simmons', forename: 'Corey', gender: 'Male', ukCity: 'Oldham', salary: '£40 to £50k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Brooks', forename: 'Leslie', gender: 'Female', ukCity: 'Gloucester', salary: 'Upto £10k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Boyd', forename: 'Gerald', gender: 'Male', ukCity: 'Rochester', salary: '£20 to £30k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Patel', forename: 'Monica', gender: 'Female', ukCity: 'Rotherham', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Medina', forename: 'Warren', gender: 'Male', ukCity: 'Sittingbourne', salary: 'Upto £10k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Henderson', forename: 'Nathan', gender: 'Male', ukCity: 'Luton', salary: '£50 to £60k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Cooper', forename: 'Warren', gender: 'Male', ukCity: 'Leeds', salary: '£30 to £40k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Jackson', forename: 'Heather', gender: 'Female', ukCity: 'Bootle', salary: '£90 and over', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Stephens', forename: 'Jeremy', gender: 'Male', ukCity: 'Bolton', salary: '£40 to £50k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Woods', forename: 'Bobby', gender: 'Male', ukCity: 'Bradford', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Brooks', forename: 'Jeffrey', gender: 'Male', ukCity: 'Kirkcaldy', salary: '£90 and over', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Murray', forename: 'Jim', gender: 'Male', ukCity: 'Stoke-on-Trent', salary: '£20 to £30k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Powell', forename: 'Denise', gender: 'Female', ukCity: 'Worcester', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Reynolds', forename: 'Norma', gender: 'Female', ukCity: 'EastKilbride', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Carter', forename: 'Marion', gender: 'Female', ukCity: 'Clacton-on-Sea', salary: '£50 to £60k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Freeman', forename: 'Tim', gender: 'Male', ukCity: 'Cheltenham', salary: '£70 to £80k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simpson', forename: 'Ernest', gender: 'Male', ukCity: 'Rochdale', salary: '£70 to £80k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Roberts', forename: 'Jorge', gender: 'Male', ukCity: 'Bolton', salary: 'Upto £10k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Long', forename: 'Jack', gender: 'Male', ukCity: 'Corby', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Fisher', forename: 'Bertha', gender: 'Female', ukCity: 'Lowestoft', salary: '£80 to £90k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Owens', forename: 'Gloria', gender: 'Female', ukCity: 'Grays', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Brown', forename: 'Martha', gender: 'Female', ukCity: 'EllesmerePort', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Smith', forename: 'Cheryl', gender: 'Female', ukCity: 'Solihull', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Young', forename: 'James', gender: 'Male', ukCity: 'Gravesend', salary: '£70 to £80k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Payne', forename: 'Frances', gender: 'Female', ukCity: 'Norwich', salary: 'Upto £10k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gomez', forename: 'Bryan', gender: 'Male', ukCity: 'Wolverhampton', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ruiz', forename: 'Jon', gender: 'Male', ukCity: 'Doncaster', salary: '£40 to £50k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Woods', forename: 'Sheila', gender: 'Female', ukCity: 'Cheltenham', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Long', forename: 'Ruth', gender: 'Female', ukCity: 'Keighley', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'James', forename: 'Alfred', gender: 'Male', ukCity: 'Lisburn', salary: '£30 to £40k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ortiz', forename: 'Jerome', gender: 'Male', ukCity: 'Rugby', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Medina', forename: 'Martha', gender: 'Female', ukCity: 'Maidenhead', salary: '£10 to £20k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Porter', forename: 'Randy', gender: 'Male', ukCity: 'Canterbury', salary: '£90 and over', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Kim', forename: 'Jerry', gender: 'Male', ukCity: 'Cannock', salary: '£90 and over', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Schmidt', forename: 'Dana', gender: 'Female', ukCity: 'Brentwood', salary: '£20 to £30k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Porter', forename: 'Lucille', gender: 'Female', ukCity: 'Ewell', salary: '£90 and over', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Castro', forename: 'Janet', gender: 'Female', ukCity: 'Gillingham', salary: '£10 to £20k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gonzalez', forename: 'Louise', gender: 'Female', ukCity: 'Stourbridge', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Morgan', forename: 'Jerry', gender: 'Male', ukCity: 'Derby', salary: '£40 to £50k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Elliott', forename: 'Bernice', gender: 'Female', ukCity: 'Weston-super-Mare', salary: '£50 to £60k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thompson', forename: 'June', gender: 'Female', ukCity: 'Paisley', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Stewart', forename: 'Richard', gender: 'Male', ukCity: 'Worcester', salary: '£80 to £90k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Young', forename: 'Alicia', gender: 'Female', ukCity: 'Chester', salary: '£50 to £60k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Price', forename: 'Andrew', gender: 'Male', ukCity: 'Kingston-upon-Hull', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wood', forename: 'Helen', gender: 'Female', ukCity: 'Leicester', salary: '£30 to £40k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Rose', forename: 'Ida', gender: 'Female', ukCity: 'Hamilton', salary: '£10 to £20k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Woods', forename: 'Amanda', gender: 'Female', ukCity: 'Basildon', salary: '£30 to £40k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Pierce', forename: 'Alice', gender: 'Female', ukCity: 'Doncaster', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wagner', forename: 'Megan', gender: 'Female', ukCity: 'Shoreham-by-Sea', salary: '£40 to £50k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Mcdonald', forename: 'Earl', gender: 'Male', ukCity: 'Exeter', salary: '£20 to £30k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gomez', forename: 'Ray', gender: 'Male', ukCity: 'Blackpool', salary: '£40 to £50k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Chavez', forename: 'Herbert', gender: 'Male', ukCity: 'Swindon', salary: '£20 to £30k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Moreno', forename: 'Vernon', gender: 'Male', ukCity: 'Paignton', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Lee', forename: 'Leroy', gender: 'Male', ukCity: 'Hereford', salary: '£30 to £40k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Clark', forename: 'Robin', gender: 'Female', ukCity: 'Blackburn', salary: '£60 to £70k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gutierrez', forename: 'Terry', gender: 'Male', ukCity: 'Hartlepool', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Taylor', forename: 'Frank', gender: 'Male', ukCity: 'Stockton-on-Tees', salary: '£20 to £30k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gibson', forename: 'Billy', gender: 'Male', ukCity: 'Maidenhead', salary: '£40 to £50k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hart', forename: 'Gladys', gender: 'Female', ukCity: 'Rochester', salary: '£50 to £60k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ortiz', forename: 'Peggy', gender: 'Female', ukCity: 'York', salary: '£90 and over', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ramirez', forename: 'Steve', gender: 'Male', ukCity: 'Rayleigh', salary: '£60 to £70k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hunt', forename: 'Julia', gender: 'Female', ukCity: 'Southend-on-Sea', salary: '£90 and over', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simmons', forename: 'Pamela', gender: 'Female', ukCity: 'Corby', salary: '£20 to £30k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Kennedy', forename: 'Sandra', gender: 'Female', ukCity: 'Stafford', salary: '£40 to £50k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hamilton', forename: 'Leon', gender: 'Male', ukCity: 'London', salary: '£10 to £20k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Payne', forename: 'Alma', gender: 'Female', ukCity: 'Littlehampton', salary: '£90 and over', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Richardson', forename: 'Cindy', gender: 'Female', ukCity: 'Weymouth', salary: '£70 to £80k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gonzales', forename: 'Benjamin', gender: 'Male', ukCity: 'Swindon', salary: '£30 to £40k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Lopez', forename: 'Tiffany', gender: 'Female', ukCity: 'Edinburgh', salary: '£90 and over', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gibson', forename: 'Tammy', gender: 'Female', ukCity: 'Kidderminster', salary: '£10 to £20k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wagner', forename: 'Jill', gender: 'Female', ukCity: 'Hastings', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Lewis', forename: 'Veronica', gender: 'Female', ukCity: 'Rugby', salary: '£40 to £50k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hunt', forename: 'Charlie', gender: 'Male', ukCity: 'StHelen’s', salary: '£90 and over', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ryan', forename: 'Alex', gender: 'Male', ukCity: 'Poole', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simpson', forename: 'Dennis', gender: 'Male', ukCity: 'Keighley', salary: '£80 to £90k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Medina', forename: 'Ricardo', gender: 'Male', ukCity: 'Kingswinford', salary: '£30 to £40k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Murray', forename: 'Gordon', gender: 'Male', ukCity: 'Hove', salary: '£60 to £70k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Moreno', forename: 'Albert', gender: 'Male', ukCity: 'Loughborough', salary: '£80 to £90k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Green', forename: 'Christine', gender: 'Female', ukCity: 'Corby', salary: '£40 to £50k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Henry', forename: 'Debra', gender: 'Female', ukCity: 'Northampton', salary: 'Upto £10k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Bennett', forename: 'Paul', gender: 'Male', ukCity: 'Weymouth', salary: '£40 to £50k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Fernandez', forename: 'Joshua', gender: 'Male', ukCity: 'Eastleigh', salary: '£70 to £80k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Cruz', forename: 'Tyler', gender: 'Male', ukCity: 'Liverpool', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hunter', forename: 'Dale', gender: 'Male', ukCity: 'StAlban’s', salary: '£40 to £50k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Weaver', forename: 'Crystal', gender: 'Female', ukCity: 'Birmingham', salary: '£80 to £90k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Woods', forename: 'Nathan', gender: 'Male', ukCity: 'Waterlooville', salary: '£40 to £50k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Davis', forename: 'Annie', gender: 'Female', ukCity: 'Norwich', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Brown', forename: 'Bill', gender: 'Male', ukCity: 'Dartford', salary: '£50 to £60k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Nelson', forename: 'Andrew', gender: 'Male', ukCity: 'Londonderry', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Jimenez', forename: 'Kristen', gender: 'Female', ukCity: 'Gosport', salary: '£50 to £60k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thompson', forename: 'Troy', gender: 'Male', ukCity: 'Southend-on-Sea', salary: '£10 to £20k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Henderson', forename: 'Regina', gender: 'Female', ukCity: 'Watford', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Simmons', forename: 'Louis', gender: 'Male', ukCity: 'Liverpool', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ortiz', forename: 'Billy', gender: 'Male', ukCity: 'Dundee', salary: '£50 to £60k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gonzales', forename: 'Louise', gender: 'Female', ukCity: 'Aylesbury', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Davis', forename: 'Jeanne', gender: 'Female', ukCity: 'Basildon', salary: '£50 to £60k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Johnson', forename: 'Lester', gender: 'Male', ukCity: 'Dunfermline', salary: '£20 to £30k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Sanders', forename: 'Herman', gender: 'Male', ukCity: 'Portsmouth', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Black', forename: 'Stacy', gender: 'Female', ukCity: 'Norwich', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Spencer', forename: 'Bobby', gender: 'Male', ukCity: 'Salford', salary: '£40 to £50k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Anderson', forename: 'Edwin', gender: 'Male', ukCity: 'Grays', salary: '£90 and over', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Daniels', forename: 'Carolyn', gender: 'Female', ukCity: 'HighWycombe', salary: '£10 to £20k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hughes', forename: 'Diane', gender: 'Female', ukCity: 'Kingston-upon-Hull', salary: '£90 and over', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Perry', forename: 'Eva', gender: 'Female', ukCity: 'York', salary: '£60 to £70k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Davis', forename: 'Anita', gender: 'Female', ukCity: 'Corby', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thomas', forename: 'Katherine', gender: 'Female', ukCity: 'Reading', salary: '£10 to £20k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Alvarez', forename: 'Andrew', gender: 'Male', ukCity: 'Dewsbury', salary: '£10 to £20k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Lee', forename: 'Patricia', gender: 'Female', ukCity: 'Bath', salary: '£60 to £70k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Daniels', forename: 'Sally', gender: 'Female', ukCity: 'Scarborough', salary: '£30 to £40k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Bell', forename: 'Betty', gender: 'Female', ukCity: 'Kettering', salary: '£90 and over', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Burns', forename: 'Mario', gender: 'Male', ukCity: 'Crewe', salary: 'Upto £10k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hayes', forename: 'Sam', gender: 'Male', ukCity: 'Nottingham', salary: '£60 to £70k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Henry', forename: 'Jorge', gender: 'Male', ukCity: 'Gosport', salary: '£50 to £60k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Alexander', forename: 'Harold', gender: 'Male', ukCity: 'Gateshead', salary: '£60 to £70k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Edwards', forename: 'Francis', gender: 'Male', ukCity: 'Harrogate', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wagner', forename: 'Joshua', gender: 'Male', ukCity: 'Eastleigh', salary: '£70 to £80k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Garcia', forename: 'Monica', gender: 'Female', ukCity: 'Luton', salary: '£90 and over', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Medina', forename: 'Micheal', gender: 'Male', ukCity: 'Crewe', salary: '£70 to £80k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Murray', forename: 'Mario', gender: 'Male', ukCity: 'Leicester', salary: '£90 and over', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thomas', forename: 'Aaron', gender: 'Male', ukCity: 'Brentwood', salary: '£30 to £40k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Garcia', forename: 'Darlene', gender: 'Female', ukCity: 'Doncaster', salary: '£80 to £90k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gonzales', forename: 'Herman', gender: 'Male', ukCity: 'Woking', salary: '£60 to £70k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Daniels', forename: 'Joanne', gender: 'Female', ukCity: 'Kingston-upon-Hull', salary: '£90 and over', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hall', forename: 'Samuel', gender: 'Male', ukCity: 'Paisley', salary: '£50 to £60k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thomas', forename: 'Shannon', gender: 'Female', ukCity: 'Grimsby', salary: '£90 and over', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hunter', forename: 'Jason', gender: 'Male', ukCity: 'Christchurch', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Morales', forename: 'Kristen', gender: 'Female', ukCity: 'WestBromwich', salary: '£20 to £30k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Reyes', forename: 'Peter', gender: 'Male', ukCity: 'Oldham', salary: '£60 to £70k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gordon', forename: 'Dolores', gender: 'Female', ukCity: 'Solihull', salary: '£70 to £80k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Murphy', forename: 'Darrell', gender: 'Male', ukCity: 'Macclesfield', salary: '£70 to £80k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Richardson', forename: 'Sharon', gender: 'Female', ukCity: 'Middlesbrough', salary: 'Upto £10k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Marshall', forename: 'Lewis', gender: 'Male', ukCity: 'Gloucester', salary: 'Upto £10k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Alexander', forename: 'Bernice', gender: 'Female', ukCity: 'Bedford', salary: '£60 to £70k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Morgan', forename: 'Maria', gender: 'Female', ukCity: 'Belfast', salary: '£50 to £60k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wright', forename: 'Alfred', gender: 'Male', ukCity: 'Littlehampton', salary: '£10 to £20k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gonzalez', forename: 'Katie', gender: 'Female', ukCity: 'Kirkcaldy', salary: '£60 to £70k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Meyer', forename: 'Roberto', gender: 'Male', ukCity: 'Poole', salary: '£20 to £30k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Green', forename: 'Michael', gender: 'Male', ukCity: 'Salford', salary: '£90 and over', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ruiz', forename: 'Jim', gender: 'Male', ukCity: 'Kingswinford', salary: '£20 to £30k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Gibson', forename: 'Peggy', gender: 'Female', ukCity: 'Stevenage', salary: 'Upto £10k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hawkins', forename: 'Suzanne', gender: 'Female', ukCity: 'Macclesfield', salary: '£40 to £50k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Torres', forename: 'Mike', gender: 'Male', ukCity: 'Southend-on-Sea', salary: '£80 to £90k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Holmes', forename: 'Virginia', gender: 'Female', ukCity: 'Warrington', salary: '£20 to £30k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Powell', forename: 'Melvin', gender: 'Male', ukCity: 'Smethwick', salary: '£70 to £80k', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ferguson', forename: 'Rodney', gender: 'Male', ukCity: 'Walsall', salary: '£10 to £20k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Tran', forename: 'Bruce', gender: 'Male', ukCity: 'Halesowen', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ross', forename: 'Jacob', gender: 'Male', ukCity: 'Cardiff', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Carter', forename: 'Joyce', gender: 'Female', ukCity: 'Chatham', salary: '£10 to £20k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Weaver', forename: 'Joseph', gender: 'Male', ukCity: 'Clacton-on-Sea', salary: '£30 to £40k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Grant', forename: 'Janice', gender: 'Female', ukCity: 'Doncaster', salary: '£30 to £40k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Payne', forename: 'Larry', gender: 'Male', ukCity: 'Telford', salary: '£30 to £40k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Olson', forename: 'Warren', gender: 'Male', ukCity: 'Eastleigh', salary: '£50 to £60k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hill', forename: 'Shawn', gender: 'Male', ukCity: 'Shrewsbury', salary: '£90 and over', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Tran', forename: 'Samuel', gender: 'Male', ukCity: 'Smethwick', salary: '£30 to £40k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Lopez', forename: 'George', gender: 'Male', ukCity: 'Halesowen', salary: '£90 and over', department: 'Legal', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hernandez', forename: 'Eleanor', gender: 'Female', ukCity: 'HighWycombe', salary: '£90 and over', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hunter', forename: 'Harry', gender: 'Male', ukCity: 'Leicester', salary: '£60 to £70k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Grant', forename: 'Carolyn', gender: 'Female', ukCity: 'Tamworth', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Wells', forename: 'Thelma', gender: 'Female', ukCity: 'London', salary: '£30 to £40k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Stevens', forename: 'Rebecca', gender: 'Female', ukCity: 'Scunthorpe', salary: 'Upto £10k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thompson', forename: 'Beth', gender: 'Female', ukCity: 'Chester', salary: '£40 to £50k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ross', forename: 'Tammy', gender: 'Female', ukCity: 'Bootle', salary: '£20 to £30k', department: 'HR', isGroup:false, groupName:'', reduced:false},
  {surname: 'Carter', forename: 'Harold', gender: 'Male', ukCity: 'Scarborough', salary: '£10 to £20k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Cruz', forename: 'Joe', gender: 'Male', ukCity: 'Bangor', salary: '£70 to £80k', department: 'Operations', isGroup:false, groupName:'', reduced:false},
  {surname: 'Snyder', forename: 'Nancy', gender: 'Female', ukCity: 'Worthing', salary: '£60 to £70k', department: 'Sales', isGroup:false, groupName:'', reduced:false},
  {surname: 'Thomas', forename: 'Charlie', gender: 'Male', ukCity: 'Crewe', salary: '£80 to £90k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Williams', forename: 'Annie', gender: 'Female', ukCity: 'Ewell', salary: '£20 to £30k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Hoffman', forename: 'Jacob', gender: 'Male', ukCity: 'Swansea', salary: '£20 to £30k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Smith', forename: 'Cynthia', gender: 'Female', ukCity: 'Londonderry', salary: '£40 to £50k', department: 'IT', isGroup:false, groupName:'', reduced:false},
  {surname: 'Ferguson', forename: 'Debra', gender: 'Female', ukCity: 'Salford', salary: '£50 to £60k', department: 'Marketing', isGroup:false, groupName:'', reduced:false},
  {surname: 'Williams', forename: 'Charlie', gender: 'Male', ukCity: 'Crosby', salary: 'Upto £10k', department: 'Accounts', isGroup:false, groupName:'', reduced:false},
];
